Feature/chart
Mark-Krensel/capstone-project pull request #23
Opened 2022-11-01 14:32 UTC by Mark-Krensel

Hello please look at my new feature "the cart".

2022-11-01 14:33 UTC, Mark-Krensel commented on pages/weight.js
> +  const ascendingFilteredDays = Array.from(filteredDays).reverse();
Is it good practice to clone an array, to display it once ascending and descending the other time on the same page?

2022-11-01 15:02 UTC, ThomasF85 requested changes
Please have a look at my comments.
You are using Chart.js without a matching component library. That's why you have to use useRef and Constructors and this probably unfamiliar syntax. I recommend using react-chartjs-2: https://www.npmjs.com/package/react-chartjs-2 . This library works with Chart.js and gives you components directly.

2022-11-01 15:02 UTC, ThomasF85 commented on pages/weight.js
> +  const ascendingFilteredDays = Array.from(filteredDays).reverse();
You can definitely do that. If you don't clone the array here you would manipulate it using reverse => leading to a bug, because you still need the array in original order down below

2022-11-01 15:02 UTC, ThomasF85 commented on pages/weight.js
> +  console.table(ascendingFilteredDays);
Please remove console logs

2022-11-01 15:02 UTC, ThomasF85 commented on pages/weight.js
> +  };
Constants that don't depend on state can be outside of the component (above the function ... line), so they don't get recreated every time the component renders.

2022-11-01 21:15 UTC, Mark-Krensel commented on pages/weight.js
> +  console.table(ascendingFilteredDays);
deleted

2022-11-01 21:16 UTC, Mark-Krensel commented on pages/weight.js
> +  };
moved out of function

2022-11-01 21:18 UTC, Mark-Krensel commented
Hello @ThomasF85 , I switched to react-chartjs-2, and remade the chart into a component.
Please have a look again :)

2022-11-02 14:37 UTC, ThomasF85 approved these changes
Looks good!

2022-11-02 15:34 UTC, merged